/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -N -e --unamed-opts --output-dir=./src --src-output-dir=./src -i ./src/chain.ggo --file-name=chaincmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "chaincmdline.h"

const char *gengetopt_args_info_purpose = "Search congressional district markov chain.";

const char *gengetopt_args_info_usage = "Usage: chain -n steps -f filename";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_full_help[] = {
  "  -h, --help                    Print help and exit",
  "      --full-help               Print help, including hidden options, and exit",
  "      --version                 Print version and exit",
  "\nMain:",
  "  -X, --statistic=STRING        statistical test  (possible values=\"rootep\",\n                                  \"GCserial\", \"starsplit\", \"GCparallel\"\n                                  default=`rootep')",
  "  -n, --steps=LONGLONG          do 2^n steps",
  "  -N, --numdists=INT            number of districts  (default=`7')",
  "  -f, --filename=filename       name of district file",
  "  -d, --period=INT              2^d is period for output  (default=`22')",
  "  -Z, --only-end                only output final results  (default=off)",
  "  -V, --variance                report variance statistics  (default=off)",
  "  -M, --median_mean             report median/mean test statistics\n                                  (default=off)",
  "  -B, --partisan_bias           report partisan bias test statistics\n                                  (default=off)",
  "  -u  --BG_uniform              report uniform geometric bias test statistics\n                                  (default=off)",
  "  -m  --BG_modified             report modified geometric bias test statistics\n                                 (default=off)",
  "  -L, --seat_slide              report seat-slide test statistics\n                                  (default=off)",
  "  -E, --efficiency_gap          report efficiency gap test statistics\n                                  (default=off)",
  "  -S, --seats                   report seat count test statistics\n                                  (default=off)",
  "  -H, --histogram               output seat count histogram [HEURISTIC]\n                                  (default=off)",
  "  -F, --freeze=INT              list of districts to leave unchanged (e.g., for\n                                  existing M/M districts)",
  "  -C, --counties                preserve any counties currently belonging to a\n                                  unique district  (default=off)",
  "  -p, --poperror=FLOAT          population percent error allowed\n                                  (default=`.02')",
  "  -P, --perimeter=FLOAT         districting perimeter threshold",
  "  -c, --polsby-popper=FLOAT     Polsby-Popper compactness threshold",
  "  -1, --L1-compactness=FLOAT    threshold for sum of Polsby-Popper values",
  "  -2, --L2-compactness=FLOAT    threshold for L2 norm of Polsby-Popper values",
  "  -I, --inputsvg-filename=filename\n                                filename of svg input  (default=`input.svg')",
  "  -s, --svg-filename=filename   svg filename  (default=`districting')",
  "  -o, --precinct-filename=filename\n                                precinct filename  (default=`OutputPA')",
  "  -l, --svg-firstline=INT       first rgb line of input.svg  (default=`20')",
  "  -O, --stages                  output files for intermediate stages\n                                  (default=off)",
  "  -R, --flip                    flip A/B party correspondence  (default=off)",
  "  -t, --threads=INT             number of threads to use (starsplit branches)",
  "  -b, --branches=INT            2^b is number of branches to use for GCparallel\n                                  (default=`8')",
  "      --seed=INT                seed offset (for benchmarking)  (default=`0')",
    0
};

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_full_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_full_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_full_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_full_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_full_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_full_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_full_help[6];
  gengetopt_args_info_help[7] = gengetopt_args_info_full_help[7];
  gengetopt_args_info_help[8] = gengetopt_args_info_full_help[8];
  gengetopt_args_info_help[9] = gengetopt_args_info_full_help[9];
  gengetopt_args_info_help[10] = gengetopt_args_info_full_help[10];
  gengetopt_args_info_help[11] = gengetopt_args_info_full_help[11];
  gengetopt_args_info_help[12] = gengetopt_args_info_full_help[12];
  gengetopt_args_info_help[13] = gengetopt_args_info_full_help[13];
  gengetopt_args_info_help[14] = gengetopt_args_info_full_help[14];
  gengetopt_args_info_help[15] = gengetopt_args_info_full_help[15];
  gengetopt_args_info_help[16] = gengetopt_args_info_full_help[16];
  gengetopt_args_info_help[17] = gengetopt_args_info_full_help[17];
  gengetopt_args_info_help[18] = gengetopt_args_info_full_help[19];
  gengetopt_args_info_help[19] = gengetopt_args_info_full_help[20];
  gengetopt_args_info_help[20] = gengetopt_args_info_full_help[21];
  gengetopt_args_info_help[21] = gengetopt_args_info_full_help[22];
  gengetopt_args_info_help[22] = gengetopt_args_info_full_help[23];
  gengetopt_args_info_help[23] = gengetopt_args_info_full_help[24];
  gengetopt_args_info_help[24] = gengetopt_args_info_full_help[25];
  gengetopt_args_info_help[25] = gengetopt_args_info_full_help[26];
  gengetopt_args_info_help[26] = gengetopt_args_info_full_help[27];
  gengetopt_args_info_help[27] = gengetopt_args_info_full_help[28];
  gengetopt_args_info_help[28] = gengetopt_args_info_full_help[29];
  gengetopt_args_info_help[29] = gengetopt_args_info_full_help[30];
  gengetopt_args_info_help[30] = gengetopt_args_info_full_help[31];
  gengetopt_args_info_help[31] = gengetopt_args_info_full_help[32];
  gengetopt_args_info_help[32] = gengetopt_args_info_full_help[33];
  gengetopt_args_info_help[33] = 0; 
  
}

const char *gengetopt_args_info_help[34];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
  , ARG_LONGLONG
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_statistic_values[] = {"rootep", "GCserial", "starsplit", "GCparallel", 0}; /*< Possible values for statistic. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->statistic_given = 0 ;
  args_info->steps_given = 0 ;
  args_info->numdists_given = 0 ;
  args_info->filename_given = 0 ;
  args_info->period_given = 0 ;
  args_info->only_end_given = 0 ;
  args_info->variance_given = 0 ;
  args_info->median_mean_given = 0 ;
  args_info->partisan_bias_given = 0 ;
  args_info->BG_uniform_given = 0 ;
  args_info->BG_modified_given = 0 ;
  args_info->seat_slide_given = 0 ;
  args_info->efficiency_gap_given = 0 ;
  args_info->seats_given = 0 ;
  args_info->histogram_given = 0 ;
  args_info->freeze_given = 0 ;
  args_info->counties_given = 0 ;
  args_info->poperror_given = 0 ;
  args_info->perimeter_given = 0 ;
  args_info->polsby_popper_given = 0 ;
  args_info->L1_compactness_given = 0 ;
  args_info->L2_compactness_given = 0 ;
  args_info->inputsvg_filename_given = 0 ;
  args_info->svg_filename_given = 0 ;
  args_info->precinct_filename_given = 0 ;
  args_info->svg_firstline_given = 0 ;
  args_info->stages_given = 0 ;
  args_info->flip_given = 0 ;
  args_info->threads_given = 0 ;
  args_info->branches_given = 0 ;
  args_info->seed_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->statistic_arg = gengetopt_strdup ("rootep");
  args_info->statistic_orig = NULL;
  args_info->steps_orig = NULL;
  args_info->numdists_arg = 7;
  args_info->numdists_orig = NULL;
  args_info->filename_arg = NULL;
  args_info->filename_orig = NULL;
  args_info->period_arg = 22;
  args_info->period_orig = NULL;
  args_info->only_end_flag = 0;
  args_info->variance_flag = 0;
  args_info->median_mean_flag = 0;
  args_info->partisan_bias_flag = 0;
  args_info->BG_uniform_flag = 0;
  args_info->BG_modified_flag = 0;
  args_info->seat_slide_flag = 0;
  args_info->efficiency_gap_flag = 0;
  args_info->seats_flag = 0;
  args_info->histogram_flag = 0;
  args_info->freeze_arg = NULL;
  args_info->freeze_orig = NULL;
  args_info->counties_flag = 0;
  args_info->poperror_arg = .02;
  args_info->poperror_orig = NULL;
  args_info->perimeter_orig = NULL;
  args_info->polsby_popper_orig = NULL;
  args_info->L1_compactness_orig = NULL;
  args_info->L2_compactness_orig = NULL;
  args_info->inputsvg_filename_arg = gengetopt_strdup ("input.svg");
  args_info->inputsvg_filename_orig = NULL;
  args_info->svg_filename_arg = gengetopt_strdup ("districting");
  args_info->svg_filename_orig = NULL;
  args_info->precinct_filename_arg = gengetopt_strdup ("OutputPA");
  args_info->precinct_filename_orig = NULL;
  args_info->svg_firstline_arg = 20;
  args_info->svg_firstline_orig = NULL;
  args_info->stages_flag = 0;
  args_info->flip_flag = 0;
  args_info->threads_orig = NULL;
  args_info->branches_arg = 8;
  args_info->branches_orig = NULL;
  args_info->seed_arg = 0;
  args_info->seed_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{

  init_help_array(); 
  args_info->help_help = gengetopt_args_info_full_help[0] ;
  args_info->full_help_help = gengetopt_args_info_full_help[1] ;
  args_info->version_help = gengetopt_args_info_full_help[2] ;
  args_info->statistic_help = gengetopt_args_info_full_help[4] ;
  args_info->steps_help = gengetopt_args_info_full_help[5] ;
  args_info->numdists_help = gengetopt_args_info_full_help[6] ;
  args_info->filename_help = gengetopt_args_info_full_help[7] ;
  args_info->period_help = gengetopt_args_info_full_help[8] ;
  args_info->only_end_help = gengetopt_args_info_full_help[9] ;
  args_info->variance_help = gengetopt_args_info_full_help[10] ;
  args_info->median_mean_help = gengetopt_args_info_full_help[11] ;
  args_info->partisan_bias_help = gengetopt_args_info_full_help[12] ;
  args_info->BG_uniform_help = gengetopt_args_info_full_help[13] ;
  args_info->BG_modified_help = gengetopt_args_info_full_help[14] ;
  args_info->seat_slide_help = gengetopt_args_info_full_help[15] ;
  args_info->efficiency_gap_help = gengetopt_args_info_full_help[16] ;
  args_info->seats_help = gengetopt_args_info_full_help[17] ;
  args_info->histogram_help = gengetopt_args_info_full_help[18] ;
  args_info->freeze_help = gengetopt_args_info_full_help[19] ;
  args_info->freeze_min = 0;
  args_info->freeze_max = 0;
  args_info->counties_help = gengetopt_args_info_full_help[20] ;
  args_info->poperror_help = gengetopt_args_info_full_help[21] ;
  args_info->perimeter_help = gengetopt_args_info_full_help[22] ;
  args_info->polsby_popper_help = gengetopt_args_info_full_help[23] ;
  args_info->L1_compactness_help = gengetopt_args_info_full_help[24] ;
  args_info->L2_compactness_help = gengetopt_args_info_full_help[25] ;
  args_info->inputsvg_filename_help = gengetopt_args_info_full_help[26] ;
  args_info->svg_filename_help = gengetopt_args_info_full_help[27] ;
  args_info->precinct_filename_help = gengetopt_args_info_full_help[28] ;
  args_info->svg_firstline_help = gengetopt_args_info_full_help[29] ;
  args_info->stages_help = gengetopt_args_info_full_help[30] ;
  args_info->flip_help = gengetopt_args_info_full_help[31] ;
  args_info->threads_help = gengetopt_args_info_full_help[32] ;
  args_info->branches_help = gengetopt_args_info_full_help[33] ;
  args_info->seed_help = gengetopt_args_info_full_help[34] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
    long long int longlong_arg;
#else
    long longlong_arg;
#endif
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}

/**
 * The passed arg parameter is NOT set to 0 from this function
 */
static void
free_multiple_field(unsigned int len, void *arg, char ***orig)
{
  unsigned int i;
  if (arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (arg);
    free (*orig);
    *orig = 0;
  }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->statistic_arg));
  free_string_field (&(args_info->statistic_orig));
  free_string_field (&(args_info->steps_orig));
  free_string_field (&(args_info->numdists_orig));
  free_string_field (&(args_info->filename_arg));
  free_string_field (&(args_info->filename_orig));
  free_string_field (&(args_info->period_orig));
  free_multiple_field (args_info->freeze_given, (void *)(args_info->freeze_arg), &(args_info->freeze_orig));
  args_info->freeze_arg = 0;
  free_string_field (&(args_info->poperror_orig));
  free_string_field (&(args_info->perimeter_orig));
  free_string_field (&(args_info->polsby_popper_orig));
  free_string_field (&(args_info->L1_compactness_orig));
  free_string_field (&(args_info->L2_compactness_orig));
  free_string_field (&(args_info->inputsvg_filename_arg));
  free_string_field (&(args_info->inputsvg_filename_orig));
  free_string_field (&(args_info->svg_filename_arg));
  free_string_field (&(args_info->svg_filename_orig));
  free_string_field (&(args_info->precinct_filename_arg));
  free_string_field (&(args_info->precinct_filename_orig));
  free_string_field (&(args_info->svg_firstline_orig));
  free_string_field (&(args_info->threads_orig));
  free_string_field (&(args_info->branches_orig));
  free_string_field (&(args_info->seed_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->statistic_given)
    write_into_file(outfile, "statistic", args_info->statistic_orig, cmdline_parser_statistic_values);
  if (args_info->steps_given)
    write_into_file(outfile, "steps", args_info->steps_orig, 0);
  if (args_info->numdists_given)
    write_into_file(outfile, "numdists", args_info->numdists_orig, 0);
  if (args_info->filename_given)
    write_into_file(outfile, "filename", args_info->filename_orig, 0);
  if (args_info->period_given)
    write_into_file(outfile, "period", args_info->period_orig, 0);
  if (args_info->only_end_given)
    write_into_file(outfile, "only-end", 0, 0 );
  if (args_info->variance_given)
    write_into_file(outfile, "variance", 0, 0 );
  if (args_info->median_mean_given)
    write_into_file(outfile, "median_mean", 0, 0 );
  if (args_info->partisan_bias_given)
    write_into_file(outfile, "partisan_bias", 0, 0 );
  if (args_info->BG_uniform_given)
	write_into_file(outfile, "BG_uniform", 0, 0 );
  if (args_info->BG_modified_given)
	write_into_file(outfile, "BG_modified", 0, 0 );
  if (args_info->seat_slide_given)
    write_into_file(outfile, "seat_slide", 0, 0 );
  if (args_info->efficiency_gap_given)
    write_into_file(outfile, "efficiency_gap", 0, 0 );
  if (args_info->seats_given)
    write_into_file(outfile, "seats", 0, 0 );
  if (args_info->histogram_given)
    write_into_file(outfile, "histogram", 0, 0 );
  write_multiple_into_file(outfile, args_info->freeze_given, "freeze", args_info->freeze_orig, 0);
  if (args_info->counties_given)
    write_into_file(outfile, "counties", 0, 0 );
  if (args_info->poperror_given)
    write_into_file(outfile, "poperror", args_info->poperror_orig, 0);
  if (args_info->perimeter_given)
    write_into_file(outfile, "perimeter", args_info->perimeter_orig, 0);
  if (args_info->polsby_popper_given)
    write_into_file(outfile, "polsby-popper", args_info->polsby_popper_orig, 0);
  if (args_info->L1_compactness_given)
    write_into_file(outfile, "L1-compactness", args_info->L1_compactness_orig, 0);
  if (args_info->L2_compactness_given)
    write_into_file(outfile, "L2-compactness", args_info->L2_compactness_orig, 0);
  if (args_info->inputsvg_filename_given)
    write_into_file(outfile, "inputsvg-filename", args_info->inputsvg_filename_orig, 0);
  if (args_info->svg_filename_given)
    write_into_file(outfile, "svg-filename", args_info->svg_filename_orig, 0);
  if (args_info->precinct_filename_given)
    write_into_file(outfile, "precinct-filename", args_info->precinct_filename_orig, 0);
  if (args_info->svg_firstline_given)
    write_into_file(outfile, "svg-firstline", args_info->svg_firstline_orig, 0);
  if (args_info->stages_given)
    write_into_file(outfile, "stages", 0, 0 );
  if (args_info->flip_given)
    write_into_file(outfile, "flip", 0, 0 );
  if (args_info->threads_given)
    write_into_file(outfile, "threads", args_info->threads_orig, 0);
  if (args_info->branches_given)
    write_into_file(outfile, "branches", args_info->branches_orig, 0);
  if (args_info->seed_given)
    write_into_file(outfile, "seed", args_info->seed_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->steps_given)
    {
      fprintf (stderr, "%s: '--steps' ('-n') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->filename_given)
    {
      fprintf (stderr, "%s: '--filename' ('-f') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (check_multiple_option_occurrences(prog_name, args_info->freeze_given, args_info->freeze_min, args_info->freeze_max, "'--freeze' ('-F')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
    if (val) *((long long int*)field) = (long long int) strtoll (val, &stop_char, 0);
#else
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
#endif
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
  case ARG_LONGLONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
      *((long long int **)field) = (long long int *)realloc (*((long long int **)field), (field_given + prev_given) * sizeof (long long int)); break;
#else
      *((long **)field) = (long *)realloc (*((long **)field), (field_given + prev_given) * sizeof (long)); break;
#endif
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
          (*((long long int **)field))[i + field_given] = tmp->arg.longlong_arg; break;
#else
          (*((long **)field))[i + field_given] = tmp->arg.longlong_arg; break;
#endif
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
        if (! *((long long int **)field)) {
          *((long long int **)field) = (long long int *)malloc (sizeof (long long int));
          (*((long long int **)field))[0] = default_value->longlong_arg;
        }
#else
        if (! *((long **)field)) {
          *((long **)field) = (long *)malloc (sizeof (long));
          (*((long **)field))[0] = default_value->longlong_arg;
        }
#endif
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * freeze_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 0 },
        { "statistic",	1, NULL, 'X' },
        { "steps",	1, NULL, 'n' },
        { "numdists",	1, NULL, 'N' },
        { "filename",	1, NULL, 'f' },
        { "period",	1, NULL, 'd' },
        { "only-end",	0, NULL, 'Z' },
        { "variance",	0, NULL, 'V' },
        { "median_mean",	0, NULL, 'M' },
        { "partisan_bias",	0, NULL, 'B' },
		{ "BG_uniform", 0, NULL, 'u' },
		{ "BG_modified", 0, NULL, 'm' },
        { "seat_slide",	0, NULL, 'L' },
        { "efficiency_gap",	0, NULL, 'E' },
        { "seats",	0, NULL, 'S' },
        { "histogram",	0, NULL, 'H' },
        { "freeze",	1, NULL, 'F' },
        { "counties",	0, NULL, 'C' },
        { "poperror",	1, NULL, 'p' },
        { "perimeter",	1, NULL, 'P' },
        { "polsby-popper",	1, NULL, 'c' },
        { "L1-compactness",	1, NULL, '1' },
        { "L2-compactness",	1, NULL, '2' },
        { "inputsvg-filename",	1, NULL, 'I' },
        { "svg-filename",	1, NULL, 's' },
        { "precinct-filename",	1, NULL, 'o' },
        { "svg-firstline",	1, NULL, 'l' },
        { "stages",	0, NULL, 'O' },
        { "flip",	0, NULL, 'R' },
        { "threads",	1, NULL, 't' },
        { "branches",	1, NULL, 'b' },
        { "seed",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hX:n:N:f:d:ZVMBumLESHF:Cp:P:c:1:2:I:s:o:l:ORt:b:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'X':	/* statistical test.  */
        
        
          if (update_arg( (void *)&(args_info->statistic_arg), 
               &(args_info->statistic_orig), &(args_info->statistic_given),
              &(local_args_info.statistic_given), optarg, cmdline_parser_statistic_values, "rootep", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "statistic", 'X',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* do 2^n steps.  */
        
        
          if (update_arg( (void *)&(args_info->steps_arg), 
               &(args_info->steps_orig), &(args_info->steps_given),
              &(local_args_info.steps_given), optarg, 0, 0, ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "steps", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'N':	/* number of districts.  */
        
        
          if (update_arg( (void *)&(args_info->numdists_arg), 
               &(args_info->numdists_orig), &(args_info->numdists_given),
              &(local_args_info.numdists_given), optarg, 0, "7", ARG_INT,
              check_ambiguity, override, 0, 0,
              "numdists", 'N',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* name of district file.  */
        
        
          if (update_arg( (void *)&(args_info->filename_arg), 
               &(args_info->filename_orig), &(args_info->filename_given),
              &(local_args_info.filename_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "filename", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* 2^d is period for output.  */
        
        
          if (update_arg( (void *)&(args_info->period_arg), 
               &(args_info->period_orig), &(args_info->period_given),
              &(local_args_info.period_given), optarg, 0, "22", ARG_INT,
              check_ambiguity, override, 0, 0,
              "period", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'Z':	/* only output final results.  */
        
        
          if (update_arg((void *)&(args_info->only_end_flag), 0, &(args_info->only_end_given),
              &(local_args_info.only_end_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "only-end", 'Z',
              additional_error))
            goto failure;
        
          break;
        case 'V':	/* report variance statistics.  */
        
        
          if (update_arg((void *)&(args_info->variance_flag), 0, &(args_info->variance_given),
              &(local_args_info.variance_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "variance", 'V',
              additional_error))
            goto failure;
        
          break;
        case 'M':	/* report median/mean test statistics.  */
        
        
          if (update_arg((void *)&(args_info->median_mean_flag), 0, &(args_info->median_mean_given),
              &(local_args_info.median_mean_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "median_mean", 'M',
              additional_error))
            goto failure;
        
          break;
        case 'B':	/* report partisan bias test statistics.  */
        
        
          if (update_arg((void *)&(args_info->partisan_bias_flag), 0, &(args_info->partisan_bias_given),
              &(local_args_info.partisan_bias_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "partisan_bias", 'B',
              additional_error))
            goto failure;
        
          break;
		case 'u': /* report uniform geometric bias test statistics. */
		
		
		  if (update_arg((void *)&(args_info->BG_uniform_flag), 0, &(args_info->BG_uniform_given),
		      &(local_args_info.BG_uniform_given), optarg, 0, 0, ARG_FLAG,
			  check_ambiguity, override, 1, 0, "BG_uniform", 'u',
			  additional_error))
			goto failure;
			
		  break;
		case 'm': /* report modified geometric bias test statistics. */
		
		
		  if (update_arg((void *)&(args_info->BG_modified_flag), 0, &(args_info->BG_modified_given),
		      &(local_args_info.BG_modified_given), optarg, 0, 0, ARG_FLAG,
			  check_ambiguity, override, 1, 0, "BG_modified", 'm',
			  additional_error))
			goto failure;
			
		  break;
        case 'L':	/* report seat-slide test statistics.  */
        
        
          if (update_arg((void *)&(args_info->seat_slide_flag), 0, &(args_info->seat_slide_given),
              &(local_args_info.seat_slide_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "seat_slide", 'L',
              additional_error))
            goto failure;
        
          break;
        case 'E':	/* report efficiency gap test statistics.  */
        
        
          if (update_arg((void *)&(args_info->efficiency_gap_flag), 0, &(args_info->efficiency_gap_given),
              &(local_args_info.efficiency_gap_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "efficiency_gap", 'E',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* report seat count test statistics.  */
        
        
          if (update_arg((void *)&(args_info->seats_flag), 0, &(args_info->seats_given),
              &(local_args_info.seats_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "seats", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'H':	/* output seat count histogram [HEURISTIC].  */
        
        
          if (update_arg((void *)&(args_info->histogram_flag), 0, &(args_info->histogram_given),
              &(local_args_info.histogram_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "histogram", 'H',
              additional_error))
            goto failure;
        
          break;
        case 'F':	/* list of districts to leave unchanged (e.g., for existing M/M districts).  */
        
          if (update_multiple_arg_temp(&freeze_list, 
              &(local_args_info.freeze_given), optarg, 0, 0, ARG_INT,
              "freeze", 'F',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* preserve any counties currently belonging to a unique district.  */
        
        
          if (update_arg((void *)&(args_info->counties_flag), 0, &(args_info->counties_given),
              &(local_args_info.counties_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "counties", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* population percent error allowed.  */
        
        
          if (update_arg( (void *)&(args_info->poperror_arg), 
               &(args_info->poperror_orig), &(args_info->poperror_given),
              &(local_args_info.poperror_given), optarg, 0, ".02", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "poperror", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* districting perimeter threshold.  */
        
        
          if (update_arg( (void *)&(args_info->perimeter_arg), 
               &(args_info->perimeter_orig), &(args_info->perimeter_given),
              &(local_args_info.perimeter_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "perimeter", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Polsby-Popper compactness threshold.  */
        
        
          if (update_arg( (void *)&(args_info->polsby_popper_arg), 
               &(args_info->polsby_popper_orig), &(args_info->polsby_popper_given),
              &(local_args_info.polsby_popper_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "polsby-popper", 'c',
              additional_error))
            goto failure;
        
          break;
        case '1':	/* threshold for sum of Polsby-Popper values.  */
        
        
          if (update_arg( (void *)&(args_info->L1_compactness_arg), 
               &(args_info->L1_compactness_orig), &(args_info->L1_compactness_given),
              &(local_args_info.L1_compactness_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "L1-compactness", '1',
              additional_error))
            goto failure;
        
          break;
        case '2':	/* threshold for L2 norm of Polsby-Popper values.  */
        
        
          if (update_arg( (void *)&(args_info->L2_compactness_arg), 
               &(args_info->L2_compactness_orig), &(args_info->L2_compactness_given),
              &(local_args_info.L2_compactness_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "L2-compactness", '2',
              additional_error))
            goto failure;
        
          break;
        case 'I':	/* filename of svg input.  */
        
        
          if (update_arg( (void *)&(args_info->inputsvg_filename_arg), 
               &(args_info->inputsvg_filename_orig), &(args_info->inputsvg_filename_given),
              &(local_args_info.inputsvg_filename_given), optarg, 0, "input.svg", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "inputsvg-filename", 'I',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* svg filename.  */
        
        
          if (update_arg( (void *)&(args_info->svg_filename_arg), 
               &(args_info->svg_filename_orig), &(args_info->svg_filename_given),
              &(local_args_info.svg_filename_given), optarg, 0, "districting", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "svg-filename", 's',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* precinct filename.  */
        
        
          if (update_arg( (void *)&(args_info->precinct_filename_arg), 
               &(args_info->precinct_filename_orig), &(args_info->precinct_filename_given),
              &(local_args_info.precinct_filename_given), optarg, 0, "OutputPA", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "precinct-filename", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* first rgb line of input.svg.  */
        
        
          if (update_arg( (void *)&(args_info->svg_firstline_arg), 
               &(args_info->svg_firstline_orig), &(args_info->svg_firstline_given),
              &(local_args_info.svg_firstline_given), optarg, 0, "20", ARG_INT,
              check_ambiguity, override, 0, 0,
              "svg-firstline", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'O':	/* output files for intermediate stages.  */
        
        
          if (update_arg((void *)&(args_info->stages_flag), 0, &(args_info->stages_given),
              &(local_args_info.stages_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "stages", 'O',
              additional_error))
            goto failure;
        
          break;
        case 'R':	/* flip A/B party correspondence.  */
        
        
          if (update_arg((void *)&(args_info->flip_flag), 0, &(args_info->flip_given),
              &(local_args_info.flip_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "flip", 'R',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* number of threads to use (starsplit branches).  */
        
        
          if (update_arg( (void *)&(args_info->threads_arg), 
               &(args_info->threads_orig), &(args_info->threads_given),
              &(local_args_info.threads_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "threads", 't',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* 2^b is number of branches to use for GCparallel.  */
        
        
          if (update_arg( (void *)&(args_info->branches_arg), 
               &(args_info->branches_orig), &(args_info->branches_given),
              &(local_args_info.branches_given), optarg, 0, "8", ARG_INT,
              check_ambiguity, override, 0, 0,
              "branches", 'b',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Print version and exit.  */
          if (strcmp (long_options[option_index].name, "version") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->version_given),
                &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "version", 'V',
                additional_error))
              goto failure;
            cmdline_parser_free (&local_args_info);
            return 0;
          
          }
          /* seed offset (for benchmarking).  */
          else if (strcmp (long_options[option_index].name, "seed") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->seed_arg), 
                 &(args_info->seed_orig), &(args_info->seed_given),
                &(local_args_info.seed_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "seed", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->freeze_arg),
    &(args_info->freeze_orig), args_info->freeze_given,
    local_args_info.freeze_given, 0,
    ARG_INT, freeze_list);

  args_info->freeze_given += local_args_info.freeze_given;
  local_args_info.freeze_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (freeze_list, 0 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
